name: 'Cloudfront distribution deploy'
description: 'Deploys a cloudfront distribution with the given parameters'
author: 'cinch-labs'
inputs:
  cloudformation-stack-name:
    required: true
    description: 'The cloudformation stack for the deployment'
  a-record-name:
    required: false
    description: 'The name of the A record to be created if required'
    default: ''
  cloudfront-aliases:
    required: true
    description: 'A comma separated list of the aliases to associate with the cloudfront distribution. The first item in the list will be used as the output of the action.'
    default: ''
  lambda-stack-name:
    required: false
    description: 'The stack name of the rewrite/auth lambda for the deployment'
    default: ''
  route-53-zone-name:
    required: true
    description: 'The Route 53 zone name for the deployment'
  s3-bucket-name:
    required: true
    description: 'The name of the S3 bucket where the site bundle will be deployed to'
  subdirectory-name:
    required: true
    description: 'The name of the subdirectory in S3 bucket where the site bundle will be deployed to'
  aws-region:
    required: true
    description: 'The AWS region where cloudformation stack will be deployed to'
  certificate-name:
    required: false
    description: 'If you want to manually specify a certificate name'
    default: ''
  web-acl-id:
    required: false
    description: 'The Web ACL ID - see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-distributionconfig.html#cfn-cloudfront-distribution-distributionconfig-webaclid for full information on this parameter'
    default: ''

runs:
  using: 'node12'
  main: 'dist/index.js'
